_target_: sbcnn_sed.model.models.SBCNNSed
num_classes: 10
in_channels: 1
input_shape: [32, 64]
conv_blocks:
  - out_channels: 64
    kernel_size: 5
    pool: true
  - out_channels: 64
    kernel_size: 5
    pool: true
  - out_channels: 64
    kernel_size: 5
    pool: false
fc_hidden: 64
dropout: 0.5
pool_size: 2 